/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InitdialogComponent {
        "closeDialog": () => Promise<void>;
        "is"?: string;
        "openDialog": () => Promise<void>;
        "text"?: string;
        "toggleFn"?: string;
    }
    interface NesbuttonComponent {
        "fileInput"?: boolean;
        "is"?: "primary" | "success" | "warning" | "error" | "disabled";
        "text"?: string;
    }
    interface NescheckboxComponent {
        "checked"?: boolean;
        "isDark"?: boolean;
        "label"?: string;
    }
    interface NescontainerComponent {
        "containerStyle"?: string;
        "isCentered"?: boolean;
        "isDark"?: boolean;
        "isRounded"?: boolean;
        "titleText"?: string;
    }
    interface NesdialogComponent {
        "closeDialog": () => Promise<void>;
        "isDark"?: boolean;
        "isRounded"?: boolean;
        "openDialog": () => Promise<void>;
        "options"?: string;
        "titleText"?: string;
    }
    interface NesdialogbtnComponent {
        "closeDialog": () => Promise<void>;
        "dialogId"?: string;
        "is"?: string;
        "openDialog": () => Promise<void>;
        "text"?: string;
        "toggleFn"?: string;
    }
    interface NesinputComponent {
        "fieldType"?: "name" | "inline" | "warning" | "error" | "dark";
        "inline"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "status"?: "green" | "yellow" | "red" | "black";
    }
    interface NesradioComponent {
        "isDark"?: boolean;
        "label"?: string;
        "name": string;
        "value": string;
    }
    interface NesselectComponent {
        "attrs"?: string;
        "fieldType"?: 'default' | 'success' | 'warning' | 'error' | 'dark';
        "label"?: string;
        "options"?: string;
    }
    interface NestextComponent {
        "element"?: keyof HTMLElementTagNameMap;
        "is"?: 'primary' | 'success' | 'warning' | 'error' | 'disabled';
        "options"?: string;
        "text": string;
    }
    interface NestextareaComponent {
        "label": string;
    }
}
declare global {
    interface HTMLInitdialogComponentElement extends Components.InitdialogComponent, HTMLStencilElement {
    }
    var HTMLInitdialogComponentElement: {
        prototype: HTMLInitdialogComponentElement;
        new (): HTMLInitdialogComponentElement;
    };
    interface HTMLNesbuttonComponentElement extends Components.NesbuttonComponent, HTMLStencilElement {
    }
    var HTMLNesbuttonComponentElement: {
        prototype: HTMLNesbuttonComponentElement;
        new (): HTMLNesbuttonComponentElement;
    };
    interface HTMLNescheckboxComponentElement extends Components.NescheckboxComponent, HTMLStencilElement {
    }
    var HTMLNescheckboxComponentElement: {
        prototype: HTMLNescheckboxComponentElement;
        new (): HTMLNescheckboxComponentElement;
    };
    interface HTMLNescontainerComponentElement extends Components.NescontainerComponent, HTMLStencilElement {
    }
    var HTMLNescontainerComponentElement: {
        prototype: HTMLNescontainerComponentElement;
        new (): HTMLNescontainerComponentElement;
    };
    interface HTMLNesdialogComponentElement extends Components.NesdialogComponent, HTMLStencilElement {
    }
    var HTMLNesdialogComponentElement: {
        prototype: HTMLNesdialogComponentElement;
        new (): HTMLNesdialogComponentElement;
    };
    interface HTMLNesdialogbtnComponentElement extends Components.NesdialogbtnComponent, HTMLStencilElement {
    }
    var HTMLNesdialogbtnComponentElement: {
        prototype: HTMLNesdialogbtnComponentElement;
        new (): HTMLNesdialogbtnComponentElement;
    };
    interface HTMLNesinputComponentElement extends Components.NesinputComponent, HTMLStencilElement {
    }
    var HTMLNesinputComponentElement: {
        prototype: HTMLNesinputComponentElement;
        new (): HTMLNesinputComponentElement;
    };
    interface HTMLNesradioComponentElement extends Components.NesradioComponent, HTMLStencilElement {
    }
    var HTMLNesradioComponentElement: {
        prototype: HTMLNesradioComponentElement;
        new (): HTMLNesradioComponentElement;
    };
    interface HTMLNesselectComponentElement extends Components.NesselectComponent, HTMLStencilElement {
    }
    var HTMLNesselectComponentElement: {
        prototype: HTMLNesselectComponentElement;
        new (): HTMLNesselectComponentElement;
    };
    interface HTMLNestextComponentElement extends Components.NestextComponent, HTMLStencilElement {
    }
    var HTMLNestextComponentElement: {
        prototype: HTMLNestextComponentElement;
        new (): HTMLNestextComponentElement;
    };
    interface HTMLNestextareaComponentElement extends Components.NestextareaComponent, HTMLStencilElement {
    }
    var HTMLNestextareaComponentElement: {
        prototype: HTMLNestextareaComponentElement;
        new (): HTMLNestextareaComponentElement;
    };
    interface HTMLElementTagNameMap {
        "initdialog-component": HTMLInitdialogComponentElement;
        "nesbutton-component": HTMLNesbuttonComponentElement;
        "nescheckbox-component": HTMLNescheckboxComponentElement;
        "nescontainer-component": HTMLNescontainerComponentElement;
        "nesdialog-component": HTMLNesdialogComponentElement;
        "nesdialogbtn-component": HTMLNesdialogbtnComponentElement;
        "nesinput-component": HTMLNesinputComponentElement;
        "nesradio-component": HTMLNesradioComponentElement;
        "nesselect-component": HTMLNesselectComponentElement;
        "nestext-component": HTMLNestextComponentElement;
        "nestextarea-component": HTMLNestextareaComponentElement;
    }
}
declare namespace LocalJSX {
    interface InitdialogComponent {
        "is"?: string;
        "text"?: string;
        "toggleFn"?: string;
    }
    interface NesbuttonComponent {
        "fileInput"?: boolean;
        "is"?: "primary" | "success" | "warning" | "error" | "disabled";
        "text"?: string;
    }
    interface NescheckboxComponent {
        "checked"?: boolean;
        "isDark"?: boolean;
        "label"?: string;
    }
    interface NescontainerComponent {
        "containerStyle"?: string;
        "isCentered"?: boolean;
        "isDark"?: boolean;
        "isRounded"?: boolean;
        "titleText"?: string;
    }
    interface NesdialogComponent {
        "isDark"?: boolean;
        "isRounded"?: boolean;
        "options"?: string;
        "titleText"?: string;
    }
    interface NesdialogbtnComponent {
        "dialogId"?: string;
        "is"?: string;
        "text"?: string;
        "toggleFn"?: string;
    }
    interface NesinputComponent {
        "fieldType"?: "name" | "inline" | "warning" | "error" | "dark";
        "inline"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "status"?: "green" | "yellow" | "red" | "black";
    }
    interface NesradioComponent {
        "isDark"?: boolean;
        "label"?: string;
        "name"?: string;
        "value"?: string;
    }
    interface NesselectComponent {
        "attrs"?: string;
        "fieldType"?: 'default' | 'success' | 'warning' | 'error' | 'dark';
        "label"?: string;
        "options"?: string;
    }
    interface NestextComponent {
        "element"?: keyof HTMLElementTagNameMap;
        "is"?: 'primary' | 'success' | 'warning' | 'error' | 'disabled';
        "options"?: string;
        "text"?: string;
    }
    interface NestextareaComponent {
        "label"?: string;
    }
    interface IntrinsicElements {
        "initdialog-component": InitdialogComponent;
        "nesbutton-component": NesbuttonComponent;
        "nescheckbox-component": NescheckboxComponent;
        "nescontainer-component": NescontainerComponent;
        "nesdialog-component": NesdialogComponent;
        "nesdialogbtn-component": NesdialogbtnComponent;
        "nesinput-component": NesinputComponent;
        "nesradio-component": NesradioComponent;
        "nesselect-component": NesselectComponent;
        "nestext-component": NestextComponent;
        "nestextarea-component": NestextareaComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "initdialog-component": LocalJSX.InitdialogComponent & JSXBase.HTMLAttributes<HTMLInitdialogComponentElement>;
            "nesbutton-component": LocalJSX.NesbuttonComponent & JSXBase.HTMLAttributes<HTMLNesbuttonComponentElement>;
            "nescheckbox-component": LocalJSX.NescheckboxComponent & JSXBase.HTMLAttributes<HTMLNescheckboxComponentElement>;
            "nescontainer-component": LocalJSX.NescontainerComponent & JSXBase.HTMLAttributes<HTMLNescontainerComponentElement>;
            "nesdialog-component": LocalJSX.NesdialogComponent & JSXBase.HTMLAttributes<HTMLNesdialogComponentElement>;
            "nesdialogbtn-component": LocalJSX.NesdialogbtnComponent & JSXBase.HTMLAttributes<HTMLNesdialogbtnComponentElement>;
            "nesinput-component": LocalJSX.NesinputComponent & JSXBase.HTMLAttributes<HTMLNesinputComponentElement>;
            "nesradio-component": LocalJSX.NesradioComponent & JSXBase.HTMLAttributes<HTMLNesradioComponentElement>;
            "nesselect-component": LocalJSX.NesselectComponent & JSXBase.HTMLAttributes<HTMLNesselectComponentElement>;
            "nestext-component": LocalJSX.NestextComponent & JSXBase.HTMLAttributes<HTMLNestextComponentElement>;
            "nestextarea-component": LocalJSX.NestextareaComponent & JSXBase.HTMLAttributes<HTMLNestextareaComponentElement>;
        }
    }
}
